# Generated by Django 2.0.2 on 2020-06-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20200615_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='numero',
        ),
    ]
