# Generated by Django 2.0.2 on 2020-06-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20200617_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='CNPJ'),
        ),
    ]
