# Generated by Django 2.0.2 on 2020-06-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20200617_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hora',
            field=models.IntegerField(blank=True, default=5, verbose_name='Meia hora'),
        ),
    ]
