# Generated by Django 2.0.2 on 2020-07-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_user_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vagas',
            new_name='vacancies',
        ),
    ]
