# Generated by Django 2.0.2 on 2020-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20200703_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pais',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hora',
        ),
        migrations.AddField(
            model_name='user',
            name='value_hour',
            field=models.IntegerField(blank=True, default=5, verbose_name='Valor por hora'),
        ),
    ]
