# Generated by Django 2.0.2 on 2020-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20200703_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, verbose_name='CNPJ'),
        ),
    ]
