# Generated by Django 2.0.2 on 2020-07-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_auto_20200707_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='value_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=4, max_digits=10, verbose_name='Valor por hora'),
        ),
    ]
