# Generated by Django 3.0.7 on 2020-06-15 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=80, verbose_name='Placa veiculo')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo do carro')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca do veiculo')),
                ('ano', models.CharField(max_length=80, verbose_name='Ano de fabricacao')),
                ('cor', models.CharField(max_length=80, verbose_name='Cor do veiculo')),
                ('proprietario', models.CharField(max_length=80, verbose_name='Nome do dono')),
                ('h_entrada', models.DateTimeField()),
                ('h_saida', models.DateTimeField()),
                ('idEstacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_vei', to=settings.AUTH_USER_MODEL, verbose_name='Estacionamento id')),
                ('idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='employees.Empregados', verbose_name='Funcionario id')),
            ],
        ),
    ]
