# Generated by Django 2.0.2 on 2020-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0003_auto_20200615_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='h_entrada',
            field=models.CharField(default='', max_length=80, verbose_name='Data entrada'),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='h_saida',
            field=models.CharField(default='', max_length=80, verbose_name='Data Saida'),
        ),
    ]
