# Generated by Django 2.0.2 on 2020-06-21 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0004_auto_20200617_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='h_entrada',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data entrada'),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='h_saida',
            field=models.DateTimeField(verbose_name='Data Saida'),
        ),
    ]
