# Generated by Django 2.0.2 on 2020-07-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0005_auto_20200621_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculos',
            old_name='placa',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='cor',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='h_entrada',
            new_name='h_enter',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='h_saida',
            new_name='h_exit',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='proprietario',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='ano',
            new_name='year',
        ),
    ]
