# Generated by Django 2.0.2 on 2020-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0007_auto_20200703_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='board',
            field=models.CharField(max_length=80, unique=True, verbose_name='Placa veiculo'),
        ),
    ]
