# Generated by Django 2.0.2 on 2020-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0008_auto_20200707_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='board',
            field=models.CharField(max_length=7, unique=True, verbose_name='Placa veiculo'),
        ),
    ]
