# Generated by Django 2.0.2 on 2020-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0009_auto_20200707_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='board',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa veiculo'),
        ),
    ]
