# Generated by Django 3.0.7 on 2020-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome do funcionario')),
                ('credential', models.CharField(blank=True, max_length=9, verbose_name='Identificação')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=50, verbose_name='Cpf')),
                ('rg', models.CharField(blank=True, max_length=50, verbose_name='Rg')),
                ('localidade', models.CharField(default='', max_length=80, verbose_name='Localidade')),
                ('cargo', models.CharField(default='', max_length=80, verbose_name='cargo')),
                ('dt_nasc', models.CharField(default='', max_length=80, verbose_name='Data Nascimento')),
                ('dt_ini', models.CharField(default='', max_length=80, verbose_name='Data entrada')),
                ('dt_end', models.CharField(default='', max_length=80, verbose_name='Data Saida')),
            ],
        ),
    ]
