# Generated by Django 3.0.7 on 2020-06-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200615_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregados',
            name='idEstacionamento',
        ),
    ]
