# Generated by Django 3.0.7 on 2020-06-15 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_remove_empregados_idestacionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='idEstacionamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='establishment_emp', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Estabelecimento'),
            preserve_default=False,
        ),
    ]
