# Generated by Django 2.0.2 on 2020-06-21 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_empregados_idestacionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='dt_end',
            field=models.DateTimeField(verbose_name='Data Saida'),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='dt_ini',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data entrada'),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='dt_nasc',
            field=models.DateTimeField(verbose_name='Data Nascimento'),
        ),
    ]
