# Generated by Django 2.0.2 on 2020-07-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20200621_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empregados',
            old_name='telefone',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='empregados',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='empregados',
            old_name='localidade',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='empregados',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='empregados',
            name='cargo',
        ),
        migrations.AddField(
            model_name='empregados',
            name='office',
            field=models.CharField(default='', max_length=80, verbose_name='Cargo'),
        ),
    ]
