# Generated by Django 2.0.2 on 2020-07-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20200703_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='credential',
            field=models.CharField(blank=True, max_length=15, verbose_name='Identificação'),
        ),
    ]
