# Generated by Django 2.0.2 on 2020-07-05 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20200703_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='dt_end',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Saida'),
        ),
    ]
