# Generated by Django 2.0.2 on 2020-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20200705_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='credential',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Identificação'),
        ),
    ]
