# Generated by Django 2.0.2 on 2020-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20200707_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='rg',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Rg'),
        ),
    ]
