# Generated by Django 2.0.2 on 2020-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20200707_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='rg',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Rg'),
        ),
    ]
